name: parking
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  one_ds:
    path: ../one_ds
  print_bluetooth_thermal: ^1.1.9
  esc_pos_utils_plus: ^2.0.4
  image_halftone: ^1.0.0
  provider: ^6.1.5+1
  sqlbrite: ^2.8.0
  path_provider: ^2.1.5
  remove_diacritic: ^0.9.0
  intl: ^0.20.2
  widgets_to_image: ^2.0.1
  share_plus: ^12.0.1
  localstorage: ^6.0.0
  calendar_date_picker2: ^2.0.1
  community_charts_flutter: ^1.0.4
  pdf: ^3.11.3
  printing: ^5.14.2
  permission_handler: ^12.0.1
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.2
  upgrader: ^12.3.0
  mobile_scanner: ^7.1.4
  barcode_widget: ^2.0.4
  lottie: ^3.3.2
  app_settings: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21    
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/scanner.json
    - assets/icon/icon.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
